name: 'issue-comments-validate'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  s3-bucket:
    required: true
    description: 'S3 bucket'
  s3-key-prefix:
    required: true
    description: 'S3 object key prefix'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
